# Setting up Training data for DNN

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import random
import warnings
import pickle
warnings.filterwarnings('ignore')

In [5]:
paths = {'audio_sentiment_data' : "../../../assets/audio_sentiment_data"}

In [6]:
import os
os.listdir(paths["audio_sentiment_data"])

['checkpoints',
 'dataset',
 'fdata.csv',
 'fscaler.pickle',
 'models',
 'X.pickle',
 'y.pickle']

In [7]:
data = pd.read_csv(f'{paths["audio_sentiment_data"]}/fdata.csv')
data = data.drop(['filename'],axis=1)
data.head()

chroma_stft      rmse  spectral_centroid  spectral_bandwidth      rolloff  \
0     0.445844  0.011145        3009.672234         2340.479394  5442.931190   
1     0.325325  0.008426        2241.335526         1768.861257  3981.986178   
2     0.490765  0.003118        2879.640741         2533.908697  5423.716947   
3     0.318230  0.009758        2433.365646         1875.043505  4319.394907   
4     0.457071  0.014074        2724.128400         2376.788708  5139.727126   

   zero_crossing_rate       mfcc1      mfcc2      mfcc3      mfcc4  ...  \
0            0.230777 -493.640411  54.894440  -8.444616  16.534016  ...   
1            0.171052 -528.263245  52.908459 -14.079989   6.865144  ...   
2            0.234495 -580.208923  68.850830   2.894124  19.279501  ...   
3            0.177378 -521.317261  42.378143 -13.373665   4.339992  ...   
4            0.195463 -474.314636  71.137466 -18.543364   8.755886  ...   

     mfcc12    mfcc13    mfcc14     mfcc15    mfcc16    mfcc17    mfcc18  \
0 -5.705760 -1.397200 -5.481062  -4.642994 -1.858748 -8.324687 -1.947321   
1 -2.908869 -6.636492  1.146552  -7.027541 -4.571496 -5.158180 -2.595091   
2 -4.364916 -3.619398 -2.475109  -7.499816  1.000039 -2.342892 -2.813844   
3 -9.730662 -4.958893 -2.758935 -12.297423 -3.837129 -4.402423 -1.995043   
4 -4.235057 -4.187407  0.202647  -7.906921  3.176005 -7.534550 -3.180893   

     mfcc19    mfcc20  label  
0 -5.402768 -3.856859  angry  
1 -3.092287  1.239585  angry  
2 -1.413119  0.532943  angry  
3 -3.888264  4.337803  angry  
4 -4.172727 -0.920171  angry  

[5 rows x 27 columns]

In [3]:
feelings = data.iloc[:, -1]
encoder = LabelEncoder()
y = encoder.fit_transform(feelings)
feelings=np.unique(np.array(feelings))

In [4]:
feelings

array(['angry', 'fearful', 'happy', 'sad', 'surprised'], dtype=object)

In [5]:
X = data.iloc[:, :-1]
X.head()

chroma_stft      rmse  spectral_centroid  spectral_bandwidth      rolloff  \
0     0.445844  0.011145        3009.672234         2340.479394  5442.931190   
1     0.325325  0.008426        2241.335526         1768.861257  3981.986178   
2     0.490765  0.003118        2879.640741         2533.908697  5423.716947   
3     0.318230  0.009758        2433.365646         1875.043505  4319.394907   
4     0.457071  0.014074        2724.128400         2376.788708  5139.727126   

   zero_crossing_rate       mfcc1      mfcc2      mfcc3      mfcc4  ...  \
0            0.230777 -493.640411  54.894440  -8.444616  16.534016  ...   
1            0.171052 -528.263245  52.908459 -14.079989   6.865144  ...   
2            0.234495 -580.208923  68.850830   2.894124  19.279501  ...   
3            0.177378 -521.317261  42.378143 -13.373665   4.339992  ...   
4            0.195463 -474.314636  71.137466 -18.543364   8.755886  ...   

     mfcc11    mfcc12    mfcc13    mfcc14     mfcc15    mfcc16    mfcc17  \
0 -1.641686 -5.705760 -1.397200 -5.481062  -4.642994 -1.858748 -8.324687   
1 -4.418773 -2.908869 -6.636492  1.146552  -7.027541 -4.571496 -5.158180   
2 -6.540556 -4.364916 -3.619398 -2.475109  -7.499816  1.000039 -2.342892   
3 -5.678762 -9.730662 -4.958893 -2.758935 -12.297423 -3.837129 -4.402423   
4  0.241584 -4.235057 -4.187407  0.202647  -7.906921  3.176005 -7.534550   

     mfcc18    mfcc19    mfcc20  
0 -1.947321 -5.402768 -3.856859  
1 -2.595091 -3.092287  1.239585  
2 -2.813844 -1.413119  0.532943  
3 -1.995043 -3.888264  4.337803  
4 -3.180893 -4.172727 -0.920171  

[5 rows x 26 columns]

In [6]:
fscaler = StandardScaler().fit(X)
X = fscaler.transform(X)

In [7]:
X[0].shape

(26,)

In [8]:
X.shape

(960, 26)

In [9]:
fscaler.mean_

array([ 4.31091207e-01,  1.66388973e-02,  2.79328769e+03,  2.37718659e+03,
        5.26503326e+03,  2.07384614e-01, -5.26441579e+02,  5.02792727e+01,
       -1.16290272e+01,  7.17397832e+00, -2.04189964e+00, -7.34409062e+00,
       -8.24805085e+00, -1.08892907e+01, -9.89458987e+00, -2.73040998e+00,
       -5.40674303e+00, -4.19953077e+00, -3.09211869e+00, -1.48662192e+00,
       -3.19416804e+00, -1.30483747e+00, -4.25122738e+00, -4.62157115e-01,
       -2.22808244e+00,  3.47898459e-02])

In [10]:
fscaler.scale_

array([7.73536895e-02, 1.83289339e-02, 3.59097897e+02, 2.70572071e+02,
       6.34889038e+02, 5.47101881e-02, 1.06038607e+02, 1.68783308e+01,
       1.40735753e+01, 8.52485131e+00, 9.56604322e+00, 8.20927099e+00,
       6.65903308e+00, 6.16027865e+00, 5.48990132e+00, 4.71801704e+00,
       5.09591535e+00, 4.89006110e+00, 4.90532521e+00, 4.91533389e+00,
       4.48133871e+00, 4.56622826e+00, 4.40873647e+00, 4.14487465e+00,
       4.01413632e+00, 4.38438526e+00])

#### to scale new data save scalar object, import and use:
#### -> new_data_scaled = scaler.transform(new_data)
#### -> then predict using scaled data


### Pickling fscaler

In [11]:
fscaler

StandardScaler()

In [12]:
pickle_out = open(f'{paths["audio_sentiment_data"]}/fscaler.pickle', "wb")
pickle.dump(fscaler, pickle_out)
pickle_out.close()

### Shuffling data

In [13]:
train_data=[]
for i in range(X.shape[0]):
    train_data.append([X[i],y[i]])

In [14]:
train_data

[[array([ 0.19071244, -0.29972598,  0.60257814, -0.13566512,  0.28020319,
          0.42756439,  0.30933232,  0.27343741,  0.22626879,  1.09797074,
         -0.04760971,  0.49611676,  0.30857858,  1.52054442, -1.22123414,
         -0.64143252,  0.73883823, -0.30801839,  0.34552624, -0.81264886,
         -0.32330213, -0.12130591, -0.92395171, -0.3583133 , -0.79087628,
         -0.88761572]),
  0],
 [array([-1.36730794, -0.44809195, -1.53705206, -2.24829313, -2.02089972,
         -0.66408437, -0.01717926,  0.15577287, -0.17415349, -0.03622756,
         -0.72056997,  0.14820679,  0.40645489, -0.29965168,  0.65849546,
         -0.02957777,  0.19387486,  0.26393566, -0.72255629,  0.53570605,
         -0.85540803, -0.71539547, -0.20571708, -0.51459554, -0.21529018,
          0.27479217]),
  0],
 [array([ 0.77144281, -0.73767533,  0.24047217,  0.57922501,  0.24993925,
          0.4955307 , -0.50705442,  1.10031955,  1.03194465,  1.42002742,
          0.53435937,  0.24295555, -0.31857331,  0.1

In [15]:
random.shuffle(train_data)

In [16]:
train_data

[[array([ 0.90300598, -0.64742896,  0.46887958,  0.47530583,  0.67846097,
          1.41863674, -0.59381711,  1.20687223,  0.86349618,  2.05632309,
          1.13649102,  0.55957833,  1.79737205,  0.54424248, -0.16730085,
          0.23474054,  0.70687985, -0.241494  ,  0.36217208, -0.03415674,
          0.19242957,  0.12583614, -0.92390759,  0.5239757 ,  0.67220968,
         -0.25544361]),
  3],
 [array([ 0.48420797, -0.13341573, -0.01204833,  0.70541596,  0.45878652,
         -0.36578779,  0.29535115,  0.60887851,  0.04585553, -0.37045048,
         -0.00360381,  0.81062223, -1.84972311,  0.7575875 , -0.50002243,
         -0.71747817,  0.81868444, -1.16653951,  0.12958937, -0.59217589,
         -1.26580387,  0.34878825, -1.26168595, -0.88010331,  0.31479185,
         -0.22339802]),
  2],
 [array([ 0.55637585, -0.5122207 ,  1.68275151,  1.48153355,  1.94028458,
          0.79725992, -0.38206251, -0.74179212,  0.85787057, -0.85645477,
         -0.74272839,  0.51055581,  1.83368274,  0.2

In [41]:
X = []
y = []

for features, label in train_data:
    X.append(features)
    y.append(label)
    
X = np.array(X)
y = np.array(y)

In [42]:
X

array([[-0.62987569, -0.47154374,  0.18475764, ..., -0.03601484,
        -1.00982557, -1.22200517],
       [-0.41435473, -0.87526957,  0.46237994, ..., -0.12200212,
        -0.89376603, -0.5111473 ],
       [-0.16980322,  0.67972232,  1.26831458, ...,  2.50981322,
         3.93688165,  2.37986321],
       ...,
       [ 0.4901671 , -0.81910108, -0.56593624, ...,  0.15198351,
         0.5800843 , -0.27686011],
       [-1.48357452,  1.52242174,  1.71135429, ...,  0.74021534,
        -2.2142513 , -1.1947272 ],
       [-1.0409129 ,  2.11263639,  1.07326945, ..., -2.00845819,
        -0.34916204,  0.58056615]])

In [43]:
y

array([2, 3, 1, 1, 0, 3, 1, 2, 2, 3, 3, 3, 2, 0, 3, 0, 0, 3, 1, 2, 3, 0,
       0, 1, 1, 3, 0, 0, 1, 0, 1, 3, 1, 3, 2, 1, 2, 1, 1, 0, 2, 3, 0, 3,
       3, 3, 2, 0, 2, 2, 3, 2, 3, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 1, 3,
       2, 0, 0, 2, 2, 1, 3, 1, 1, 1, 3, 3, 0, 3, 2, 0, 1, 3, 3, 3, 3, 2,
       1, 1, 2, 2, 3, 2, 0, 3, 2, 1, 3, 0, 0, 0, 3, 1, 0, 1, 1, 2, 0, 1,
       0, 3, 3, 2, 1, 1, 1, 1, 1, 0, 2, 1, 3, 2, 1, 1, 2, 2, 1, 0, 0, 0,
       0, 1, 2, 0, 2, 2, 1, 0, 1, 3, 2, 3, 3, 0, 1, 0, 0, 2, 0, 1, 3, 0,
       2, 3, 2, 0, 2, 0, 3, 3, 2, 2, 2, 1, 1, 1, 0, 3, 0, 1, 1, 1, 1, 0,
       0, 3, 1, 3, 2, 0, 1, 2, 3, 0, 3, 1, 2, 1, 2, 3, 3, 0, 3, 1, 1, 2,
       1, 1, 2, 2, 2, 2, 3, 2, 1, 2, 0, 3, 1, 0, 0, 2, 0, 2, 2, 0, 0, 2,
       1, 1, 0, 2, 2, 3, 1, 2, 2, 2, 0, 2, 2, 3, 0, 3, 1, 3, 0, 1, 1, 3,
       2, 0, 3, 3, 1, 1, 1, 3, 2, 0, 1, 0, 1, 1, 2, 2, 3, 3, 1, 0, 0, 3,
       2, 3, 1, 3, 1, 0, 2, 0, 2, 1, 2, 3, 1, 1, 3, 2, 2, 1, 2, 2, 1, 0,
       2, 1, 2, 2, 2, 0, 3, 1, 3, 1, 1, 1, 0, 1, 3,

### Pickling X and y (train data)

In [44]:
pickle_out = open(f'{paths["audio_sentiment_data"]}/X.pickle', "wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open(f'{paths["audio_sentiment_data"]}/y.pickle', "wb")
pickle.dump(y, pickle_out)
pickle_out.close()